### ISSUE TITLE
Feature: do not simplify fractions by default

### ISSUE THREAD

**Issue by vektor8891** [maxinteger/pocket-lisp-stdlib#11]
**Description:** Fractions are simplified by default (e.g. `-2/-4` will be stored as `1/2`). After the object is created, we cannot access the original values anymore which would be sometimes useful (e.g. when convert it into text: `mínusz kettő mínusz negyed`).

**Solution:** Simplification should not be applied when creating an object, only when making operations.

**Comment by maxinteger** [comment]
@vektor8891
I understand why do you need this functionality, but I have 2 problems
1. fraction number is a language feature and it should not change because of a specific application (Zsebtanár)
2. If we change fraction number then why we should do it consistent way and never simplify friction only when the user call (for example)  the `simplify` function

A possible solution would be to re-implement (mostly copy-past) the fraction number inside the Zsebtanár project with the new requirements.

**Comment by vektor8891** [comment]
@maxinteger Good points. I agree with you. Let's close this PR and find another solution.
